=begin
#SalesService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5401
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/access_token_response'
require 'openapi_client/models/empty_envelope'
require 'openapi_client/models/error_envelope'
require 'openapi_client/models/extended_sales_literature_dto'
require 'openapi_client/models/extended_sales_literature_dto_list_envelope'
require 'openapi_client/models/forgot_password_request'
require 'openapi_client/models/http_validation_problem_details'
require 'openapi_client/models/info_request'
require 'openapi_client/models/info_response'
require 'openapi_client/models/int32_envelope'
require 'openapi_client/models/login_request'
require 'openapi_client/models/loyalty_program_create_dto'
require 'openapi_client/models/loyalty_program_dto'
require 'openapi_client/models/loyalty_program_dto_envelope'
require 'openapi_client/models/loyalty_program_dto_list_envelope'
require 'openapi_client/models/loyalty_program_update_dto'
require 'openapi_client/models/point_of_sale_create_dto'
require 'openapi_client/models/point_of_sale_dto'
require 'openapi_client/models/point_of_sale_dto_envelope'
require 'openapi_client/models/point_of_sale_dto_list_envelope'
require 'openapi_client/models/point_of_sale_update_dto'
require 'openapi_client/models/refresh_request'
require 'openapi_client/models/register_request'
require 'openapi_client/models/resend_confirmation_email_request'
require 'openapi_client/models/reset_password_request'
require 'openapi_client/models/sales_literature_create_dto'
require 'openapi_client/models/sales_literature_dto'
require 'openapi_client/models/sales_literature_dto_envelope'
require 'openapi_client/models/sales_literature_dto_list_envelope'
require 'openapi_client/models/sales_literature_type_dto'
require 'openapi_client/models/sales_literature_update_dto'
require 'openapi_client/models/store_create_dto'
require 'openapi_client/models/store_dto'
require 'openapi_client/models/store_dto_envelope'
require 'openapi_client/models/store_dto_list_envelope'
require 'openapi_client/models/store_update_dto'
require 'openapi_client/models/tenant_dto'
require 'openapi_client/models/two_factor_request'
require 'openapi_client/models/two_factor_response'

# APIs
require 'openapi_client/api/completions_api'
require 'openapi_client/api/fenix_alliance_portals_website_api'
require 'openapi_client/api/loyalty_programs_api'
require 'openapi_client/api/margins_api'
require 'openapi_client/api/point_of_sales_api'
require 'openapi_client/api/sales_literatures_api'
require 'openapi_client/api/stores_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
