=begin
#IntelligenceService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CognitiveSkillToolDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CognitiveSkillToolDto do
  let(:instance) { OpenapiClient::CognitiveSkillToolDto.new }

  describe 'test an instance of CognitiveSkillToolDto' do
    it 'should create an instance of CognitiveSkillToolDto' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CognitiveSkillToolDto)
    end
  end

  describe 'test attribute "tool_key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "config_json"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
