=begin
#SupportService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5401
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ReturnPoliciesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReturnPoliciesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ReturnPoliciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReturnPoliciesApi' do
    it 'should create an instance of ReturnPoliciesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ReturnPoliciesApi)
    end
  end

  # unit tests for create_return_policy_async
  # Create a new return policy
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ItemReturnPolicyCreateDto] :item_return_policy_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_return_policy_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_return_policy_async
  # Delete a return policy
  # @param tenant_id 
  # @param return_policy_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_return_policy_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_return_policies_async
  # Retrieve a list of return policies
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ItemReturnPolicyDtoListEnvelope]
  describe 'get_return_policies_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_return_policies_count_async
  # Get the count of return policies
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_return_policies_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_return_policy_async
  # Retrieve a return policy by ID
  # @param tenant_id 
  # @param return_policy_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ItemReturnPolicyDtoEnvelope]
  describe 'get_return_policy_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_return_policy_async
  # Update a return policy
  # @param tenant_id 
  # @param return_policy_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ItemReturnPolicyUpdateDto] :item_return_policy_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_return_policy_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
