=begin
#TenantsService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PositionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PositionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PositionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PositionsApi' do
    it 'should create an instance of PositionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PositionsApi)
    end
  end

  # unit tests for create_tenant_position
  # Create a new tenant position
  # Create a new tenant position
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [TenantPositionCreateDto] :tenant_position_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_tenant_position test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_tenant_position
  # Delete a tenant position
  # Delete a tenant position
  # @param tenant_id 
  # @param tenant_position_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_tenant_position test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tenant_position_by_id
  # Retrieve a single tenant position by its ID
  # Retrieve a single tenant position by its ID
  # @param tenant_id 
  # @param tenant_position_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [TenantPositionDtoEnvelope]
  describe 'get_tenant_position_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tenant_positions
  # Retrieve a list of tenant positions
  # Retrieve a list of tenant positions
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [TenantPositionDtoListEnvelope]
  describe 'get_tenant_positions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tenant_positions_count
  # Get the count of tenant positions
  # Get the count of tenant positions
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_tenant_positions_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_tenant_position
  # Update a tenant position
  # Update a tenant position
  # @param tenant_id 
  # @param tenant_position_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [TenantPositionUpdateDto] :tenant_position_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_tenant_position test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
