=begin
#ManufacturingService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class WorkOrderUpdateDto
    attr_accessor :title

    attr_accessor :description

    attr_accessor :instructions

    attr_accessor :taxable

    attr_accessor :work_location

    attr_accessor :production_plan_id

    attr_accessor :work_order_type_id

    attr_accessor :workstation_id

    attr_accessor :currency_id

    attr_accessor :individual_id

    attr_accessor :organization_id

    attr_accessor :promised_start_date

    attr_accessor :promised_end_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'title' => :'title',
        :'description' => :'description',
        :'instructions' => :'instructions',
        :'taxable' => :'taxable',
        :'work_location' => :'workLocation',
        :'production_plan_id' => :'productionPlanId',
        :'work_order_type_id' => :'workOrderTypeId',
        :'workstation_id' => :'workstationId',
        :'currency_id' => :'currencyId',
        :'individual_id' => :'individualId',
        :'organization_id' => :'organizationId',
        :'promised_start_date' => :'promisedStartDate',
        :'promised_end_date' => :'promisedEndDate'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'title' => :'String',
        :'description' => :'String',
        :'instructions' => :'String',
        :'taxable' => :'Boolean',
        :'work_location' => :'String',
        :'production_plan_id' => :'String',
        :'work_order_type_id' => :'String',
        :'workstation_id' => :'String',
        :'currency_id' => :'String',
        :'individual_id' => :'String',
        :'organization_id' => :'String',
        :'promised_start_date' => :'Time',
        :'promised_end_date' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'title',
        :'description',
        :'instructions',
        :'taxable',
        :'work_location',
        :'production_plan_id',
        :'work_order_type_id',
        :'workstation_id',
        :'currency_id',
        :'individual_id',
        :'organization_id',
        :'promised_start_date',
        :'promised_end_date'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::WorkOrderUpdateDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::WorkOrderUpdateDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'instructions')
        self.instructions = attributes[:'instructions']
      end

      if attributes.key?(:'taxable')
        self.taxable = attributes[:'taxable']
      end

      if attributes.key?(:'work_location')
        self.work_location = attributes[:'work_location']
      end

      if attributes.key?(:'production_plan_id')
        self.production_plan_id = attributes[:'production_plan_id']
      end

      if attributes.key?(:'work_order_type_id')
        self.work_order_type_id = attributes[:'work_order_type_id']
      end

      if attributes.key?(:'workstation_id')
        self.workstation_id = attributes[:'workstation_id']
      end

      if attributes.key?(:'currency_id')
        self.currency_id = attributes[:'currency_id']
      end

      if attributes.key?(:'individual_id')
        self.individual_id = attributes[:'individual_id']
      end

      if attributes.key?(:'organization_id')
        self.organization_id = attributes[:'organization_id']
      end

      if attributes.key?(:'promised_start_date')
        self.promised_start_date = attributes[:'promised_start_date']
      end

      if attributes.key?(:'promised_end_date')
        self.promised_end_date = attributes[:'promised_end_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@title.nil? && @title.to_s.length > 255
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 255.')
      end

      if !@title.nil? && @title.to_s.length < 0
        invalid_properties.push('invalid value for "title", the character length must be great than or equal to 0.')
      end

      if !@description.nil? && @description.to_s.length > 2000
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 2000.')
      end

      if !@description.nil? && @description.to_s.length < 0
        invalid_properties.push('invalid value for "description", the character length must be great than or equal to 0.')
      end

      if !@instructions.nil? && @instructions.to_s.length > 4000
        invalid_properties.push('invalid value for "instructions", the character length must be smaller than or equal to 4000.')
      end

      if !@instructions.nil? && @instructions.to_s.length < 0
        invalid_properties.push('invalid value for "instructions", the character length must be great than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@title.nil? && @title.to_s.length > 255
      return false if !@title.nil? && @title.to_s.length < 0
      return false if !@description.nil? && @description.to_s.length > 2000
      return false if !@description.nil? && @description.to_s.length < 0
      return false if !@instructions.nil? && @instructions.to_s.length > 4000
      return false if !@instructions.nil? && @instructions.to_s.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if !title.nil? && title.to_s.length > 255
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 255.'
      end

      if !title.nil? && title.to_s.length < 0
        fail ArgumentError, 'invalid value for "title", the character length must be great than or equal to 0.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if !description.nil? && description.to_s.length > 2000
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 2000.'
      end

      if !description.nil? && description.to_s.length < 0
        fail ArgumentError, 'invalid value for "description", the character length must be great than or equal to 0.'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] instructions Value to be assigned
    def instructions=(instructions)
      if !instructions.nil? && instructions.to_s.length > 4000
        fail ArgumentError, 'invalid value for "instructions", the character length must be smaller than or equal to 4000.'
      end

      if !instructions.nil? && instructions.to_s.length < 0
        fail ArgumentError, 'invalid value for "instructions", the character length must be great than or equal to 0.'
      end

      @instructions = instructions
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          title == o.title &&
          description == o.description &&
          instructions == o.instructions &&
          taxable == o.taxable &&
          work_location == o.work_location &&
          production_plan_id == o.production_plan_id &&
          work_order_type_id == o.work_order_type_id &&
          workstation_id == o.workstation_id &&
          currency_id == o.currency_id &&
          individual_id == o.individual_id &&
          organization_id == o.organization_id &&
          promised_start_date == o.promised_start_date &&
          promised_end_date == o.promised_end_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [title, description, instructions, taxable, work_location, production_plan_id, work_order_type_id, workstation_id, currency_id, individual_id, organization_id, promised_start_date, promised_end_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
