=begin
#CatalogService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ItemImageDto
    attr_accessor :id

    attr_accessor :timestamp

    attr_accessor :tenant_id

    attr_accessor :enrollment_id

    attr_accessor :item_id

    attr_accessor :is_item_mozaic_bg

    attr_accessor :m_d5_hash

    attr_accessor :metadata

    attr_accessor :file_upload_url

    attr_accessor :file_name

    attr_accessor :title

    attr_accessor :abstract

    attr_accessor :author

    attr_accessor :key_words

    attr_accessor :notes

    attr_accessor :content_type

    attr_accessor :file_length

    attr_accessor :valid_response

    attr_accessor :social_profile_id

    attr_accessor :parent_file_upload_id

    attr_accessor :user_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'timestamp' => :'timestamp',
        :'tenant_id' => :'tenantId',
        :'enrollment_id' => :'enrollmentId',
        :'item_id' => :'itemId',
        :'is_item_mozaic_bg' => :'isItemMozaicBG',
        :'m_d5_hash' => :'mD5Hash',
        :'metadata' => :'metadata',
        :'file_upload_url' => :'fileUploadURL',
        :'file_name' => :'fileName',
        :'title' => :'title',
        :'abstract' => :'abstract',
        :'author' => :'author',
        :'key_words' => :'keyWords',
        :'notes' => :'notes',
        :'content_type' => :'contentType',
        :'file_length' => :'fileLength',
        :'valid_response' => :'validResponse',
        :'social_profile_id' => :'socialProfileId',
        :'parent_file_upload_id' => :'parentFileUploadId',
        :'user_id' => :'userId'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'timestamp' => :'Time',
        :'tenant_id' => :'String',
        :'enrollment_id' => :'String',
        :'item_id' => :'String',
        :'is_item_mozaic_bg' => :'Boolean',
        :'m_d5_hash' => :'String',
        :'metadata' => :'String',
        :'file_upload_url' => :'String',
        :'file_name' => :'String',
        :'title' => :'String',
        :'abstract' => :'String',
        :'author' => :'String',
        :'key_words' => :'String',
        :'notes' => :'String',
        :'content_type' => :'String',
        :'file_length' => :'Integer',
        :'valid_response' => :'Boolean',
        :'social_profile_id' => :'String',
        :'parent_file_upload_id' => :'String',
        :'user_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'timestamp',
        :'tenant_id',
        :'enrollment_id',
        :'item_id',
        :'m_d5_hash',
        :'metadata',
        :'file_upload_url',
        :'file_name',
        :'title',
        :'abstract',
        :'author',
        :'key_words',
        :'notes',
        :'content_type',
        :'social_profile_id',
        :'parent_file_upload_id',
        :'user_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ItemImageDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ItemImageDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      end

      if attributes.key?(:'enrollment_id')
        self.enrollment_id = attributes[:'enrollment_id']
      end

      if attributes.key?(:'item_id')
        self.item_id = attributes[:'item_id']
      end

      if attributes.key?(:'is_item_mozaic_bg')
        self.is_item_mozaic_bg = attributes[:'is_item_mozaic_bg']
      end

      if attributes.key?(:'m_d5_hash')
        self.m_d5_hash = attributes[:'m_d5_hash']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'file_upload_url')
        self.file_upload_url = attributes[:'file_upload_url']
      end

      if attributes.key?(:'file_name')
        self.file_name = attributes[:'file_name']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'abstract')
        self.abstract = attributes[:'abstract']
      end

      if attributes.key?(:'author')
        self.author = attributes[:'author']
      end

      if attributes.key?(:'key_words')
        self.key_words = attributes[:'key_words']
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      end

      if attributes.key?(:'file_length')
        self.file_length = attributes[:'file_length']
      end

      if attributes.key?(:'valid_response')
        self.valid_response = attributes[:'valid_response']
      end

      if attributes.key?(:'social_profile_id')
        self.social_profile_id = attributes[:'social_profile_id']
      end

      if attributes.key?(:'parent_file_upload_id')
        self.parent_file_upload_id = attributes[:'parent_file_upload_id']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          timestamp == o.timestamp &&
          tenant_id == o.tenant_id &&
          enrollment_id == o.enrollment_id &&
          item_id == o.item_id &&
          is_item_mozaic_bg == o.is_item_mozaic_bg &&
          m_d5_hash == o.m_d5_hash &&
          metadata == o.metadata &&
          file_upload_url == o.file_upload_url &&
          file_name == o.file_name &&
          title == o.title &&
          abstract == o.abstract &&
          author == o.author &&
          key_words == o.key_words &&
          notes == o.notes &&
          content_type == o.content_type &&
          file_length == o.file_length &&
          valid_response == o.valid_response &&
          social_profile_id == o.social_profile_id &&
          parent_file_upload_id == o.parent_file_upload_id &&
          user_id == o.user_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, timestamp, tenant_id, enrollment_id, item_id, is_item_mozaic_bg, m_d5_hash, metadata, file_upload_url, file_name, title, abstract, author, key_words, notes, content_type, file_length, valid_response, social_profile_id, parent_file_upload_id, user_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
