=begin
#ForexService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::RatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RatesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::RatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RatesApi' do
    it 'should create an instance of RatesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::RatesApi)
    end
  end

  # unit tests for get_historical_currency_rate_async
  # Get historical rate for a currency
  # Retrieves the exchange rate for a specific currency as of a specific historical date.
  # @param currency_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ExchangeRateEnvelope]
  describe 'get_historical_currency_rate_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_historical_currency_rates_async
  # Get historical currency rates
  # Retrieves exchange rates for all supported currencies as of a specific historical date.
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :date 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ForexRatesDtoEnvelope]
  describe 'get_historical_currency_rates_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_latest_currency_rate_async
  # Get latest rate for a currency
  # Retrieves the latest exchange rate for a specific currency by its identifier.
  # @param currency_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ExchangeRateEnvelope]
  describe 'get_latest_currency_rate_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_latest_currency_rates_model_async
  # Get latest currency rates
  # Retrieves the latest exchange rates for all supported currencies.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ForexRatesDtoEnvelope]
  describe 'get_latest_currency_rates_model_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
