=begin
#ServicesService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/access_token_response'
require 'openapi_client/models/envelope'
require 'openapi_client/models/error_envelope'
require 'openapi_client/models/forgot_password_request'
require 'openapi_client/models/http_validation_problem_details'
require 'openapi_client/models/info_request'
require 'openapi_client/models/info_response'
require 'openapi_client/models/int32_envelope'
require 'openapi_client/models/login_request'
require 'openapi_client/models/refresh_request'
require 'openapi_client/models/register_request'
require 'openapi_client/models/resend_confirmation_email_request'
require 'openapi_client/models/reset_password_request'
require 'openapi_client/models/service_case_create_dto'
require 'openapi_client/models/service_case_dto'
require 'openapi_client/models/service_case_dto_envelope'
require 'openapi_client/models/service_case_dto_i_read_only_list_envelope'
require 'openapi_client/models/service_case_type_create_dto'
require 'openapi_client/models/service_case_type_dto'
require 'openapi_client/models/service_case_type_dto_envelope'
require 'openapi_client/models/service_case_type_dto_i_read_only_list_envelope'
require 'openapi_client/models/service_case_type_update_dto'
require 'openapi_client/models/service_case_update_dto'
require 'openapi_client/models/service_create_dto'
require 'openapi_client/models/service_dto'
require 'openapi_client/models/service_dto_envelope'
require 'openapi_client/models/service_dto_i_read_only_list_envelope'
require 'openapi_client/models/service_level_agreement_create_dto'
require 'openapi_client/models/service_level_agreement_dto'
require 'openapi_client/models/service_level_agreement_dto_envelope'
require 'openapi_client/models/service_level_agreement_dto_i_read_only_list_envelope'
require 'openapi_client/models/service_level_agreement_update_dto'
require 'openapi_client/models/service_level_create_dto'
require 'openapi_client/models/service_level_dto'
require 'openapi_client/models/service_level_dto_envelope'
require 'openapi_client/models/service_level_dto_i_read_only_list_envelope'
require 'openapi_client/models/service_level_update_dto'
require 'openapi_client/models/service_queue_create_dto'
require 'openapi_client/models/service_queue_dto'
require 'openapi_client/models/service_queue_dto_envelope'
require 'openapi_client/models/service_queue_dto_i_read_only_list_envelope'
require 'openapi_client/models/service_queue_update_dto'
require 'openapi_client/models/service_update_dto'
require 'openapi_client/models/two_factor_request'
require 'openapi_client/models/two_factor_response'

# APIs
require 'openapi_client/api/fenix_alliance_abs_web_api'
require 'openapi_client/api/service_case_types_api'
require 'openapi_client/api/service_cases_api'
require 'openapi_client/api/service_level_agreements_api'
require 'openapi_client/api/service_levels_api'
require 'openapi_client/api/service_queues_api'
require 'openapi_client/api/services_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
