=begin
#ContentService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5532
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class FooterOptions
    attr_accessor :number_of_columns

    attr_accessor :enable_widgets

    attr_accessor :enable_copyright_bar

    attr_accessor :center_widgets_content

    attr_accessor :center_copyright_content

    attr_accessor :enable_vertical_widget_divider_line

    attr_accessor :vertical_widget_divider_line_size

    attr_accessor :copyright_text

    attr_accessor :copyright_background_color

    attr_accessor :border_size

    attr_accessor :border_color

    attr_accessor :widget_divider_color

    attr_accessor :widget_divider

    attr_accessor :copyright_padding

    attr_accessor :widgets_area_padding

    attr_accessor :footer_area_padding

    attr_accessor :footer_background

    attr_accessor :copyright_background

    attr_accessor :headings_typography

    attr_accessor :widgets_typography

    attr_accessor :copyright_typography

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'number_of_columns' => :'numberOfColumns',
        :'enable_widgets' => :'enableWidgets',
        :'enable_copyright_bar' => :'enableCopyrightBar',
        :'center_widgets_content' => :'centerWidgetsContent',
        :'center_copyright_content' => :'centerCopyrightContent',
        :'enable_vertical_widget_divider_line' => :'enableVerticalWidgetDividerLine',
        :'vertical_widget_divider_line_size' => :'verticalWidgetDividerLineSize',
        :'copyright_text' => :'copyrightText',
        :'copyright_background_color' => :'copyrightBackgroundColor',
        :'border_size' => :'borderSize',
        :'border_color' => :'borderColor',
        :'widget_divider_color' => :'widgetDividerColor',
        :'widget_divider' => :'widgetDivider',
        :'copyright_padding' => :'copyrightPadding',
        :'widgets_area_padding' => :'widgetsAreaPadding',
        :'footer_area_padding' => :'footerAreaPadding',
        :'footer_background' => :'footerBackground',
        :'copyright_background' => :'copyrightBackground',
        :'headings_typography' => :'headingsTypography',
        :'widgets_typography' => :'widgetsTypography',
        :'copyright_typography' => :'copyrightTypography'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'number_of_columns' => :'Integer',
        :'enable_widgets' => :'Boolean',
        :'enable_copyright_bar' => :'Boolean',
        :'center_widgets_content' => :'Boolean',
        :'center_copyright_content' => :'Boolean',
        :'enable_vertical_widget_divider_line' => :'Boolean',
        :'vertical_widget_divider_line_size' => :'Integer',
        :'copyright_text' => :'String',
        :'copyright_background_color' => :'String',
        :'border_size' => :'Integer',
        :'border_color' => :'String',
        :'widget_divider_color' => :'String',
        :'widget_divider' => :'String',
        :'copyright_padding' => :'Padding',
        :'widgets_area_padding' => :'Padding',
        :'footer_area_padding' => :'Padding',
        :'footer_background' => :'Background',
        :'copyright_background' => :'Background',
        :'headings_typography' => :'Typography',
        :'widgets_typography' => :'Typography',
        :'copyright_typography' => :'Typography'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'copyright_text',
        :'copyright_background_color',
        :'border_color',
        :'widget_divider_color',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::FooterOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::FooterOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'number_of_columns')
        self.number_of_columns = attributes[:'number_of_columns']
      end

      if attributes.key?(:'enable_widgets')
        self.enable_widgets = attributes[:'enable_widgets']
      end

      if attributes.key?(:'enable_copyright_bar')
        self.enable_copyright_bar = attributes[:'enable_copyright_bar']
      end

      if attributes.key?(:'center_widgets_content')
        self.center_widgets_content = attributes[:'center_widgets_content']
      end

      if attributes.key?(:'center_copyright_content')
        self.center_copyright_content = attributes[:'center_copyright_content']
      end

      if attributes.key?(:'enable_vertical_widget_divider_line')
        self.enable_vertical_widget_divider_line = attributes[:'enable_vertical_widget_divider_line']
      end

      if attributes.key?(:'vertical_widget_divider_line_size')
        self.vertical_widget_divider_line_size = attributes[:'vertical_widget_divider_line_size']
      end

      if attributes.key?(:'copyright_text')
        self.copyright_text = attributes[:'copyright_text']
      end

      if attributes.key?(:'copyright_background_color')
        self.copyright_background_color = attributes[:'copyright_background_color']
      end

      if attributes.key?(:'border_size')
        self.border_size = attributes[:'border_size']
      end

      if attributes.key?(:'border_color')
        self.border_color = attributes[:'border_color']
      end

      if attributes.key?(:'widget_divider_color')
        self.widget_divider_color = attributes[:'widget_divider_color']
      end

      if attributes.key?(:'widget_divider')
        self.widget_divider = attributes[:'widget_divider']
      end

      if attributes.key?(:'copyright_padding')
        self.copyright_padding = attributes[:'copyright_padding']
      end

      if attributes.key?(:'widgets_area_padding')
        self.widgets_area_padding = attributes[:'widgets_area_padding']
      end

      if attributes.key?(:'footer_area_padding')
        self.footer_area_padding = attributes[:'footer_area_padding']
      end

      if attributes.key?(:'footer_background')
        self.footer_background = attributes[:'footer_background']
      end

      if attributes.key?(:'copyright_background')
        self.copyright_background = attributes[:'copyright_background']
      end

      if attributes.key?(:'headings_typography')
        self.headings_typography = attributes[:'headings_typography']
      end

      if attributes.key?(:'widgets_typography')
        self.widgets_typography = attributes[:'widgets_typography']
      end

      if attributes.key?(:'copyright_typography')
        self.copyright_typography = attributes[:'copyright_typography']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      widget_divider_validator = EnumAttributeValidator.new('String', ["None", "Solid", "Dotted", "Double", "Groove", "Ridge"])
      return false unless widget_divider_validator.valid?(@widget_divider)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] widget_divider Object to be assigned
    def widget_divider=(widget_divider)
      validator = EnumAttributeValidator.new('String', ["None", "Solid", "Dotted", "Double", "Groove", "Ridge"])
      unless validator.valid?(widget_divider)
        fail ArgumentError, "invalid value for \"widget_divider\", must be one of #{validator.allowable_values}."
      end
      @widget_divider = widget_divider
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          number_of_columns == o.number_of_columns &&
          enable_widgets == o.enable_widgets &&
          enable_copyright_bar == o.enable_copyright_bar &&
          center_widgets_content == o.center_widgets_content &&
          center_copyright_content == o.center_copyright_content &&
          enable_vertical_widget_divider_line == o.enable_vertical_widget_divider_line &&
          vertical_widget_divider_line_size == o.vertical_widget_divider_line_size &&
          copyright_text == o.copyright_text &&
          copyright_background_color == o.copyright_background_color &&
          border_size == o.border_size &&
          border_color == o.border_color &&
          widget_divider_color == o.widget_divider_color &&
          widget_divider == o.widget_divider &&
          copyright_padding == o.copyright_padding &&
          widgets_area_padding == o.widgets_area_padding &&
          footer_area_padding == o.footer_area_padding &&
          footer_background == o.footer_background &&
          copyright_background == o.copyright_background &&
          headings_typography == o.headings_typography &&
          widgets_typography == o.widgets_typography &&
          copyright_typography == o.copyright_typography
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [number_of_columns, enable_widgets, enable_copyright_bar, center_widgets_content, center_copyright_content, enable_vertical_widget_divider_line, vertical_widget_divider_line_size, copyright_text, copyright_background_color, border_size, border_color, widget_divider_color, widget_divider, copyright_padding, widgets_area_padding, footer_area_padding, footer_background, copyright_background, headings_typography, widgets_typography, copyright_typography].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
