=begin
#ContentService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5532
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ServicesOptions
    attr_accessor :drip_downloadable_content

    attr_accessor :retry_failed_payments

    attr_accessor :allow0_initial_checkout

    attr_accessor :allow_mixed_checkout

    attr_accessor :synchronise_renewals

    attr_accessor :add_to_cart_button_text

    attr_accessor :place_order_button_text

    attr_accessor :new_subscriber_role

    attr_accessor :inactive_subscriber_role

    attr_accessor :enable_automatic_payments

    attr_accessor :enable_manual_renewals

    attr_accessor :display_auto_renewal_toggle

    attr_accessor :accept_early_renewals

    attr_accessor :customer_suspensions

    attr_accessor :enable_subscription_switching_between_groups

    attr_accessor :enable_subscription_switching_between_variations

    attr_accessor :prorate_first_renewal

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'drip_downloadable_content' => :'dripDownloadableContent',
        :'retry_failed_payments' => :'retryFailedPayments',
        :'allow0_initial_checkout' => :'allow0InitialCheckout',
        :'allow_mixed_checkout' => :'allowMixedCheckout',
        :'synchronise_renewals' => :'synchroniseRenewals',
        :'add_to_cart_button_text' => :'addToCartButtonText',
        :'place_order_button_text' => :'placeOrderButtonText',
        :'new_subscriber_role' => :'newSubscriberRole',
        :'inactive_subscriber_role' => :'inactiveSubscriberRole',
        :'enable_automatic_payments' => :'enableAutomaticPayments',
        :'enable_manual_renewals' => :'enableManualRenewals',
        :'display_auto_renewal_toggle' => :'displayAutoRenewalToggle',
        :'accept_early_renewals' => :'acceptEarlyRenewals',
        :'customer_suspensions' => :'customerSuspensions',
        :'enable_subscription_switching_between_groups' => :'enableSubscriptionSwitchingBetweenGroups',
        :'enable_subscription_switching_between_variations' => :'enableSubscriptionSwitchingBetweenVariations',
        :'prorate_first_renewal' => :'prorateFirstRenewal'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'drip_downloadable_content' => :'Boolean',
        :'retry_failed_payments' => :'Boolean',
        :'allow0_initial_checkout' => :'Boolean',
        :'allow_mixed_checkout' => :'Boolean',
        :'synchronise_renewals' => :'Boolean',
        :'add_to_cart_button_text' => :'String',
        :'place_order_button_text' => :'String',
        :'new_subscriber_role' => :'String',
        :'inactive_subscriber_role' => :'String',
        :'enable_automatic_payments' => :'Integer',
        :'enable_manual_renewals' => :'Integer',
        :'display_auto_renewal_toggle' => :'Integer',
        :'accept_early_renewals' => :'Integer',
        :'customer_suspensions' => :'Integer',
        :'enable_subscription_switching_between_groups' => :'Integer',
        :'enable_subscription_switching_between_variations' => :'Integer',
        :'prorate_first_renewal' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'add_to_cart_button_text',
        :'place_order_button_text',
        :'new_subscriber_role',
        :'inactive_subscriber_role',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ServicesOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ServicesOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'drip_downloadable_content')
        self.drip_downloadable_content = attributes[:'drip_downloadable_content']
      end

      if attributes.key?(:'retry_failed_payments')
        self.retry_failed_payments = attributes[:'retry_failed_payments']
      end

      if attributes.key?(:'allow0_initial_checkout')
        self.allow0_initial_checkout = attributes[:'allow0_initial_checkout']
      end

      if attributes.key?(:'allow_mixed_checkout')
        self.allow_mixed_checkout = attributes[:'allow_mixed_checkout']
      end

      if attributes.key?(:'synchronise_renewals')
        self.synchronise_renewals = attributes[:'synchronise_renewals']
      end

      if attributes.key?(:'add_to_cart_button_text')
        self.add_to_cart_button_text = attributes[:'add_to_cart_button_text']
      end

      if attributes.key?(:'place_order_button_text')
        self.place_order_button_text = attributes[:'place_order_button_text']
      end

      if attributes.key?(:'new_subscriber_role')
        self.new_subscriber_role = attributes[:'new_subscriber_role']
      end

      if attributes.key?(:'inactive_subscriber_role')
        self.inactive_subscriber_role = attributes[:'inactive_subscriber_role']
      end

      if attributes.key?(:'enable_automatic_payments')
        self.enable_automatic_payments = attributes[:'enable_automatic_payments']
      end

      if attributes.key?(:'enable_manual_renewals')
        self.enable_manual_renewals = attributes[:'enable_manual_renewals']
      end

      if attributes.key?(:'display_auto_renewal_toggle')
        self.display_auto_renewal_toggle = attributes[:'display_auto_renewal_toggle']
      end

      if attributes.key?(:'accept_early_renewals')
        self.accept_early_renewals = attributes[:'accept_early_renewals']
      end

      if attributes.key?(:'customer_suspensions')
        self.customer_suspensions = attributes[:'customer_suspensions']
      end

      if attributes.key?(:'enable_subscription_switching_between_groups')
        self.enable_subscription_switching_between_groups = attributes[:'enable_subscription_switching_between_groups']
      end

      if attributes.key?(:'enable_subscription_switching_between_variations')
        self.enable_subscription_switching_between_variations = attributes[:'enable_subscription_switching_between_variations']
      end

      if attributes.key?(:'prorate_first_renewal')
        self.prorate_first_renewal = attributes[:'prorate_first_renewal']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      prorate_first_renewal_validator = EnumAttributeValidator.new('String', ["AlwaysAndNoCharge", "NeverAndNoCharge", "NeverAndFullCharge", "AlwaysAndFullCharge", "ForVirtualProductsOnly", "ForServiceProductsOnly", "ForSubscriptionProductsOnly"])
      return false unless prorate_first_renewal_validator.valid?(@prorate_first_renewal)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] prorate_first_renewal Object to be assigned
    def prorate_first_renewal=(prorate_first_renewal)
      validator = EnumAttributeValidator.new('String', ["AlwaysAndNoCharge", "NeverAndNoCharge", "NeverAndFullCharge", "AlwaysAndFullCharge", "ForVirtualProductsOnly", "ForServiceProductsOnly", "ForSubscriptionProductsOnly"])
      unless validator.valid?(prorate_first_renewal)
        fail ArgumentError, "invalid value for \"prorate_first_renewal\", must be one of #{validator.allowable_values}."
      end
      @prorate_first_renewal = prorate_first_renewal
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          drip_downloadable_content == o.drip_downloadable_content &&
          retry_failed_payments == o.retry_failed_payments &&
          allow0_initial_checkout == o.allow0_initial_checkout &&
          allow_mixed_checkout == o.allow_mixed_checkout &&
          synchronise_renewals == o.synchronise_renewals &&
          add_to_cart_button_text == o.add_to_cart_button_text &&
          place_order_button_text == o.place_order_button_text &&
          new_subscriber_role == o.new_subscriber_role &&
          inactive_subscriber_role == o.inactive_subscriber_role &&
          enable_automatic_payments == o.enable_automatic_payments &&
          enable_manual_renewals == o.enable_manual_renewals &&
          display_auto_renewal_toggle == o.display_auto_renewal_toggle &&
          accept_early_renewals == o.accept_early_renewals &&
          customer_suspensions == o.customer_suspensions &&
          enable_subscription_switching_between_groups == o.enable_subscription_switching_between_groups &&
          enable_subscription_switching_between_variations == o.enable_subscription_switching_between_variations &&
          prorate_first_renewal == o.prorate_first_renewal
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [drip_downloadable_content, retry_failed_payments, allow0_initial_checkout, allow_mixed_checkout, synchronise_renewals, add_to_cart_button_text, place_order_button_text, new_subscriber_role, inactive_subscriber_role, enable_automatic_payments, enable_manual_renewals, display_auto_renewal_toggle, accept_early_renewals, customer_suspensions, enable_subscription_switching_between_groups, enable_subscription_switching_between_variations, prorate_first_renewal].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
