=begin
#ServicesService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ServiceLevelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceLevelsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ServiceLevelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceLevelsApi' do
    it 'should create an instance of ServiceLevelsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ServiceLevelsApi)
    end
  end

  # unit tests for count_all_service_levels_async
  # Get all service levels count
  # Returns the count of all service levels for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_all_service_levels_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_service_level_async
  # Create a service level
  # Creates a new service level for the specified service.
  # @param tenant_id 
  # @param service_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ServiceLevelCreateDto] :service_level_create_dto 
  # @return [Envelope]
  describe 'create_service_level_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_service_level_async
  # Delete a service level
  # Deletes a service level by its identifier.
  # @param tenant_id 
  # @param service_id 
  # @param service_level_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Envelope]
  describe 'delete_service_level_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_service_levels_async
  # Get all service levels
  # Retrieves all service levels for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ServiceLevelDtoIReadOnlyListEnvelope]
  describe 'get_all_service_levels_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service_level_by_id_async
  # Get a service level by ID
  # Retrieves a service level by its identifier.
  # @param tenant_id 
  # @param service_id 
  # @param service_level_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ServiceLevelDtoEnvelope]
  describe 'get_service_level_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service_levels_async
  # Get all service levels
  # Retrieves all service levels for the specified service.
  # @param tenant_id 
  # @param service_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ServiceLevelDtoIReadOnlyListEnvelope]
  describe 'get_service_levels_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service_levels_count_async
  # Get service levels count
  # Returns the count of service levels for the specified service.
  # @param tenant_id 
  # @param service_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_service_levels_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_service_level_async
  # Update a service level
  # Updates an existing service level.
  # @param tenant_id 
  # @param service_id 
  # @param service_level_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ServiceLevelUpdateDto] :service_level_update_dto 
  # @return [Envelope]
  describe 'update_service_level_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
