=begin
#LogisticsService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ProofOfDeliveryDto
    attr_accessor :id

    attr_accessor :timestamp

    attr_accessor :document_number

    attr_accessor :status

    attr_accessor :shipment_id

    attr_accessor :bill_of_lading_id

    attr_accessor :seaway_bill_id

    attr_accessor :airway_bill_id

    attr_accessor :road_waybill_id

    attr_accessor :rail_waybill_id

    attr_accessor :truck_trip_id

    attr_accessor :recipient_name

    attr_accessor :recipient_company_contact_id

    attr_accessor :delivery_address

    attr_accessor :delivery_date

    attr_accessor :delivery_time

    attr_accessor :signed_by

    attr_accessor :signer_identification

    attr_accessor :signature_date

    attr_accessor :digital_signature_reference

    attr_accessor :overall_condition

    attr_accessor :total_quantity_delivered

    attr_accessor :total_quantity_rejected

    attr_accessor :remarks

    attr_accessor :photo_evidence_uri

    attr_accessor :tenant_id

    attr_accessor :enrollment_id

    attr_accessor :lines

    attr_accessor :delivery_note_ids

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'timestamp' => :'timestamp',
        :'document_number' => :'documentNumber',
        :'status' => :'status',
        :'shipment_id' => :'shipmentId',
        :'bill_of_lading_id' => :'billOfLadingId',
        :'seaway_bill_id' => :'seawayBillId',
        :'airway_bill_id' => :'airwayBillId',
        :'road_waybill_id' => :'roadWaybillId',
        :'rail_waybill_id' => :'railWaybillId',
        :'truck_trip_id' => :'truckTripId',
        :'recipient_name' => :'recipientName',
        :'recipient_company_contact_id' => :'recipientCompanyContactId',
        :'delivery_address' => :'deliveryAddress',
        :'delivery_date' => :'deliveryDate',
        :'delivery_time' => :'deliveryTime',
        :'signed_by' => :'signedBy',
        :'signer_identification' => :'signerIdentification',
        :'signature_date' => :'signatureDate',
        :'digital_signature_reference' => :'digitalSignatureReference',
        :'overall_condition' => :'overallCondition',
        :'total_quantity_delivered' => :'totalQuantityDelivered',
        :'total_quantity_rejected' => :'totalQuantityRejected',
        :'remarks' => :'remarks',
        :'photo_evidence_uri' => :'photoEvidenceUri',
        :'tenant_id' => :'tenantId',
        :'enrollment_id' => :'enrollmentId',
        :'lines' => :'lines',
        :'delivery_note_ids' => :'deliveryNoteIds'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'timestamp' => :'Time',
        :'document_number' => :'String',
        :'status' => :'String',
        :'shipment_id' => :'String',
        :'bill_of_lading_id' => :'String',
        :'seaway_bill_id' => :'String',
        :'airway_bill_id' => :'String',
        :'road_waybill_id' => :'String',
        :'rail_waybill_id' => :'String',
        :'truck_trip_id' => :'String',
        :'recipient_name' => :'String',
        :'recipient_company_contact_id' => :'String',
        :'delivery_address' => :'String',
        :'delivery_date' => :'Time',
        :'delivery_time' => :'String',
        :'signed_by' => :'String',
        :'signer_identification' => :'String',
        :'signature_date' => :'Time',
        :'digital_signature_reference' => :'String',
        :'overall_condition' => :'String',
        :'total_quantity_delivered' => :'Integer',
        :'total_quantity_rejected' => :'Integer',
        :'remarks' => :'String',
        :'photo_evidence_uri' => :'String',
        :'tenant_id' => :'String',
        :'enrollment_id' => :'String',
        :'lines' => :'Array<ProofOfDeliveryLineDto>',
        :'delivery_note_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'timestamp',
        :'document_number',
        :'status',
        :'shipment_id',
        :'bill_of_lading_id',
        :'seaway_bill_id',
        :'airway_bill_id',
        :'road_waybill_id',
        :'rail_waybill_id',
        :'truck_trip_id',
        :'recipient_name',
        :'recipient_company_contact_id',
        :'delivery_address',
        :'delivery_date',
        :'delivery_time',
        :'signed_by',
        :'signer_identification',
        :'signature_date',
        :'digital_signature_reference',
        :'overall_condition',
        :'total_quantity_delivered',
        :'total_quantity_rejected',
        :'remarks',
        :'photo_evidence_uri',
        :'tenant_id',
        :'enrollment_id',
        :'lines',
        :'delivery_note_ids'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ProofOfDeliveryDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ProofOfDeliveryDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.key?(:'document_number')
        self.document_number = attributes[:'document_number']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'shipment_id')
        self.shipment_id = attributes[:'shipment_id']
      end

      if attributes.key?(:'bill_of_lading_id')
        self.bill_of_lading_id = attributes[:'bill_of_lading_id']
      end

      if attributes.key?(:'seaway_bill_id')
        self.seaway_bill_id = attributes[:'seaway_bill_id']
      end

      if attributes.key?(:'airway_bill_id')
        self.airway_bill_id = attributes[:'airway_bill_id']
      end

      if attributes.key?(:'road_waybill_id')
        self.road_waybill_id = attributes[:'road_waybill_id']
      end

      if attributes.key?(:'rail_waybill_id')
        self.rail_waybill_id = attributes[:'rail_waybill_id']
      end

      if attributes.key?(:'truck_trip_id')
        self.truck_trip_id = attributes[:'truck_trip_id']
      end

      if attributes.key?(:'recipient_name')
        self.recipient_name = attributes[:'recipient_name']
      end

      if attributes.key?(:'recipient_company_contact_id')
        self.recipient_company_contact_id = attributes[:'recipient_company_contact_id']
      end

      if attributes.key?(:'delivery_address')
        self.delivery_address = attributes[:'delivery_address']
      end

      if attributes.key?(:'delivery_date')
        self.delivery_date = attributes[:'delivery_date']
      end

      if attributes.key?(:'delivery_time')
        self.delivery_time = attributes[:'delivery_time']
      end

      if attributes.key?(:'signed_by')
        self.signed_by = attributes[:'signed_by']
      end

      if attributes.key?(:'signer_identification')
        self.signer_identification = attributes[:'signer_identification']
      end

      if attributes.key?(:'signature_date')
        self.signature_date = attributes[:'signature_date']
      end

      if attributes.key?(:'digital_signature_reference')
        self.digital_signature_reference = attributes[:'digital_signature_reference']
      end

      if attributes.key?(:'overall_condition')
        self.overall_condition = attributes[:'overall_condition']
      end

      if attributes.key?(:'total_quantity_delivered')
        self.total_quantity_delivered = attributes[:'total_quantity_delivered']
      end

      if attributes.key?(:'total_quantity_rejected')
        self.total_quantity_rejected = attributes[:'total_quantity_rejected']
      end

      if attributes.key?(:'remarks')
        self.remarks = attributes[:'remarks']
      end

      if attributes.key?(:'photo_evidence_uri')
        self.photo_evidence_uri = attributes[:'photo_evidence_uri']
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      end

      if attributes.key?(:'enrollment_id')
        self.enrollment_id = attributes[:'enrollment_id']
      end

      if attributes.key?(:'lines')
        if (value = attributes[:'lines']).is_a?(Array)
          self.lines = value
        end
      end

      if attributes.key?(:'delivery_note_ids')
        if (value = attributes[:'delivery_note_ids']).is_a?(Array)
          self.delivery_note_ids = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          timestamp == o.timestamp &&
          document_number == o.document_number &&
          status == o.status &&
          shipment_id == o.shipment_id &&
          bill_of_lading_id == o.bill_of_lading_id &&
          seaway_bill_id == o.seaway_bill_id &&
          airway_bill_id == o.airway_bill_id &&
          road_waybill_id == o.road_waybill_id &&
          rail_waybill_id == o.rail_waybill_id &&
          truck_trip_id == o.truck_trip_id &&
          recipient_name == o.recipient_name &&
          recipient_company_contact_id == o.recipient_company_contact_id &&
          delivery_address == o.delivery_address &&
          delivery_date == o.delivery_date &&
          delivery_time == o.delivery_time &&
          signed_by == o.signed_by &&
          signer_identification == o.signer_identification &&
          signature_date == o.signature_date &&
          digital_signature_reference == o.digital_signature_reference &&
          overall_condition == o.overall_condition &&
          total_quantity_delivered == o.total_quantity_delivered &&
          total_quantity_rejected == o.total_quantity_rejected &&
          remarks == o.remarks &&
          photo_evidence_uri == o.photo_evidence_uri &&
          tenant_id == o.tenant_id &&
          enrollment_id == o.enrollment_id &&
          lines == o.lines &&
          delivery_note_ids == o.delivery_note_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, timestamp, document_number, status, shipment_id, bill_of_lading_id, seaway_bill_id, airway_bill_id, road_waybill_id, rail_waybill_id, truck_trip_id, recipient_name, recipient_company_contact_id, delivery_address, delivery_date, delivery_time, signed_by, signer_identification, signature_date, digital_signature_reference, overall_condition, total_quantity_delivered, total_quantity_rejected, remarks, photo_evidence_uri, tenant_id, enrollment_id, lines, delivery_note_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
