=begin
#BlockchainsService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5532
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BlockchainsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlockchainsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BlockchainsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlockchainsApi' do
    it 'should create an instance of BlockchainsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BlockchainsApi)
    end
  end

  # unit tests for create_blockchain_async
  # Create a new blockchain
  # Creates a new blockchain for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [BlockchainCreateDto] :blockchain_create_dto 
  # @return [nil]
  describe 'create_blockchain_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_blockchain_block_async
  # Add a block to a blockchain
  # @param tenant_id 
  # @param blockchain_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [BlockchainBlockCreateDto] :blockchain_block_create_dto 
  # @return [nil]
  describe 'create_blockchain_block_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_blockchain_async
  # Delete a blockchain
  # Deletes a blockchain for the specified tenant.
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [nil]
  describe 'delete_blockchain_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_blockchain_block_async
  # Delete a blockchain block
  # @param tenant_id 
  # @param blockchain_id 
  # @param block_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [nil]
  describe 'delete_blockchain_block_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blockchain_block_by_id_async
  # Get a specific block
  # @param tenant_id 
  # @param blockchain_id 
  # @param block_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BlockchainBlockDto]
  describe 'get_blockchain_block_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blockchain_blocks_async
  # Get blocks for a blockchain
  # @param tenant_id 
  # @param blockchain_id 
  # @param [Hash] opts the optional parameters
  # @option opts [BlockchainBlockDtoODataQueryOptions] :o_data_query_options 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BlockchainBlockDtoListEnvelope]
  describe 'get_blockchain_blocks_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blockchain_blocks_count_async
  # Get block count for a blockchain
  # @param tenant_id 
  # @param blockchain_id 
  # @param [Hash] opts the optional parameters
  # @option opts [BlockchainBlockDtoODataQueryOptions] :o_data_query_options 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_blockchain_blocks_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blockchain_by_id_async
  # Get blockchain by ID
  # Retrieves a specific blockchain by its identifier.
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BlockchainDto]
  describe 'get_blockchain_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blockchains_async
  # Get all blockchains
  # Retrieves all blockchains for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [BlockchainDtoODataQueryOptions] :o_data_query_options 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BlockchainDtoListEnvelope]
  describe 'get_blockchains_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blockchains_count_async
  # Get blockchains count
  # Returns the count of blockchains for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [BlockchainDtoODataQueryOptions] :o_data_query_options 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_blockchains_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_blockchain_async
  # Patch a blockchain
  # Patch a blockchain
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [Array<Operation>] :operation 
  # @return [EmptyEnvelope]
  describe 'patch_blockchain_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_blockchain_block_async
  # Patch a blockchain block
  # Patch a blockchain block
  # @param tenant_id 
  # @param blockchain_id 
  # @param block_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [Array<Operation>] :operation 
  # @return [EmptyEnvelope]
  describe 'patch_blockchain_block_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_blockchain_async
  # Update a blockchain
  # Updates an existing blockchain for the specified tenant.
  # @param tenant_id 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [BlockchainUpdateDto] :blockchain_update_dto 
  # @return [nil]
  describe 'update_blockchain_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_blockchain_block_async
  # Update a blockchain block
  # @param tenant_id 
  # @param blockchain_id 
  # @param block_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [BlockchainBlockUpdateDto] :blockchain_block_update_dto 
  # @return [nil]
  describe 'update_blockchain_block_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
