=begin
#TrustService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ContactCreateDto
    attr_accessor :id

    attr_accessor :timestamp

    attr_accessor :type

    attr_accessor :first_name

    attr_accessor :last_name

    attr_accessor :email

    attr_accessor :tax_id

    attr_accessor :primary_contact_id

    attr_accessor :qualified_name

    attr_accessor :about

    attr_accessor :country_id

    attr_accessor :state_id

    attr_accessor :city_id

    attr_accessor :mobile_phone

    attr_accessor :business_phone

    attr_accessor :postal_code

    attr_accessor :duns

    attr_accessor :job_title

    attr_accessor :web_url

    attr_accessor :currency_id

    attr_accessor :language_id

    attr_accessor :timezone_id

    attr_accessor :birthday

    attr_accessor :street_line1

    attr_accessor :street_line2

    attr_accessor :git_hub_url

    attr_accessor :twitch_url

    attr_accessor :reddit_url

    attr_accessor :tik_tok_url

    attr_accessor :website_url

    attr_accessor :twitter_url

    attr_accessor :facebook_url

    attr_accessor :you_tube_url

    attr_accessor :linked_in_url

    attr_accessor :instagram_url

    attr_accessor :github_username

    attr_accessor :instagram_username

    attr_accessor :tik_tok_username

    attr_accessor :stack_exchange_url

    attr_accessor :stack_overflow_url

    attr_accessor :parent_contact_id

    attr_accessor :fax_number

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'timestamp' => :'timestamp',
        :'type' => :'type',
        :'first_name' => :'firstName',
        :'last_name' => :'lastName',
        :'email' => :'email',
        :'tax_id' => :'taxId',
        :'primary_contact_id' => :'primaryContactId',
        :'qualified_name' => :'qualifiedName',
        :'about' => :'about',
        :'country_id' => :'countryId',
        :'state_id' => :'stateId',
        :'city_id' => :'cityId',
        :'mobile_phone' => :'mobilePhone',
        :'business_phone' => :'businessPhone',
        :'postal_code' => :'postalCode',
        :'duns' => :'duns',
        :'job_title' => :'jobTitle',
        :'web_url' => :'webUrl',
        :'currency_id' => :'currencyId',
        :'language_id' => :'languageId',
        :'timezone_id' => :'timezoneId',
        :'birthday' => :'birthday',
        :'street_line1' => :'streetLine1',
        :'street_line2' => :'streetLine2',
        :'git_hub_url' => :'gitHubUrl',
        :'twitch_url' => :'twitchUrl',
        :'reddit_url' => :'redditUrl',
        :'tik_tok_url' => :'tikTokUrl',
        :'website_url' => :'websiteUrl',
        :'twitter_url' => :'twitterUrl',
        :'facebook_url' => :'facebookUrl',
        :'you_tube_url' => :'youTubeUrl',
        :'linked_in_url' => :'linkedInUrl',
        :'instagram_url' => :'instagramUrl',
        :'github_username' => :'githubUsername',
        :'instagram_username' => :'instagramUsername',
        :'tik_tok_username' => :'tikTokUsername',
        :'stack_exchange_url' => :'stackExchangeUrl',
        :'stack_overflow_url' => :'stackOverflowUrl',
        :'parent_contact_id' => :'parentContactId',
        :'fax_number' => :'faxNumber'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'timestamp' => :'Time',
        :'type' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'email' => :'String',
        :'tax_id' => :'String',
        :'primary_contact_id' => :'String',
        :'qualified_name' => :'String',
        :'about' => :'String',
        :'country_id' => :'String',
        :'state_id' => :'String',
        :'city_id' => :'String',
        :'mobile_phone' => :'String',
        :'business_phone' => :'String',
        :'postal_code' => :'String',
        :'duns' => :'String',
        :'job_title' => :'String',
        :'web_url' => :'String',
        :'currency_id' => :'String',
        :'language_id' => :'String',
        :'timezone_id' => :'String',
        :'birthday' => :'Time',
        :'street_line1' => :'String',
        :'street_line2' => :'String',
        :'git_hub_url' => :'String',
        :'twitch_url' => :'String',
        :'reddit_url' => :'String',
        :'tik_tok_url' => :'String',
        :'website_url' => :'String',
        :'twitter_url' => :'String',
        :'facebook_url' => :'String',
        :'you_tube_url' => :'String',
        :'linked_in_url' => :'String',
        :'instagram_url' => :'String',
        :'github_username' => :'String',
        :'instagram_username' => :'String',
        :'tik_tok_username' => :'String',
        :'stack_exchange_url' => :'String',
        :'stack_overflow_url' => :'String',
        :'parent_contact_id' => :'String',
        :'fax_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'last_name',
        :'tax_id',
        :'primary_contact_id',
        :'qualified_name',
        :'about',
        :'country_id',
        :'state_id',
        :'city_id',
        :'mobile_phone',
        :'business_phone',
        :'postal_code',
        :'duns',
        :'job_title',
        :'web_url',
        :'currency_id',
        :'language_id',
        :'timezone_id',
        :'birthday',
        :'street_line1',
        :'street_line2',
        :'git_hub_url',
        :'twitch_url',
        :'reddit_url',
        :'tik_tok_url',
        :'website_url',
        :'twitter_url',
        :'facebook_url',
        :'you_tube_url',
        :'linked_in_url',
        :'instagram_url',
        :'github_username',
        :'instagram_username',
        :'tik_tok_username',
        :'stack_exchange_url',
        :'stack_overflow_url',
        :'parent_contact_id',
        :'fax_number'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ContactCreateDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ContactCreateDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      else
        self.first_name = nil
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'tax_id')
        self.tax_id = attributes[:'tax_id']
      end

      if attributes.key?(:'primary_contact_id')
        self.primary_contact_id = attributes[:'primary_contact_id']
      end

      if attributes.key?(:'qualified_name')
        self.qualified_name = attributes[:'qualified_name']
      end

      if attributes.key?(:'about')
        self.about = attributes[:'about']
      end

      if attributes.key?(:'country_id')
        self.country_id = attributes[:'country_id']
      end

      if attributes.key?(:'state_id')
        self.state_id = attributes[:'state_id']
      end

      if attributes.key?(:'city_id')
        self.city_id = attributes[:'city_id']
      end

      if attributes.key?(:'mobile_phone')
        self.mobile_phone = attributes[:'mobile_phone']
      end

      if attributes.key?(:'business_phone')
        self.business_phone = attributes[:'business_phone']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end

      if attributes.key?(:'duns')
        self.duns = attributes[:'duns']
      end

      if attributes.key?(:'job_title')
        self.job_title = attributes[:'job_title']
      end

      if attributes.key?(:'web_url')
        self.web_url = attributes[:'web_url']
      end

      if attributes.key?(:'currency_id')
        self.currency_id = attributes[:'currency_id']
      end

      if attributes.key?(:'language_id')
        self.language_id = attributes[:'language_id']
      end

      if attributes.key?(:'timezone_id')
        self.timezone_id = attributes[:'timezone_id']
      end

      if attributes.key?(:'birthday')
        self.birthday = attributes[:'birthday']
      end

      if attributes.key?(:'street_line1')
        self.street_line1 = attributes[:'street_line1']
      end

      if attributes.key?(:'street_line2')
        self.street_line2 = attributes[:'street_line2']
      end

      if attributes.key?(:'git_hub_url')
        self.git_hub_url = attributes[:'git_hub_url']
      end

      if attributes.key?(:'twitch_url')
        self.twitch_url = attributes[:'twitch_url']
      end

      if attributes.key?(:'reddit_url')
        self.reddit_url = attributes[:'reddit_url']
      end

      if attributes.key?(:'tik_tok_url')
        self.tik_tok_url = attributes[:'tik_tok_url']
      end

      if attributes.key?(:'website_url')
        self.website_url = attributes[:'website_url']
      end

      if attributes.key?(:'twitter_url')
        self.twitter_url = attributes[:'twitter_url']
      end

      if attributes.key?(:'facebook_url')
        self.facebook_url = attributes[:'facebook_url']
      end

      if attributes.key?(:'you_tube_url')
        self.you_tube_url = attributes[:'you_tube_url']
      end

      if attributes.key?(:'linked_in_url')
        self.linked_in_url = attributes[:'linked_in_url']
      end

      if attributes.key?(:'instagram_url')
        self.instagram_url = attributes[:'instagram_url']
      end

      if attributes.key?(:'github_username')
        self.github_username = attributes[:'github_username']
      end

      if attributes.key?(:'instagram_username')
        self.instagram_username = attributes[:'instagram_username']
      end

      if attributes.key?(:'tik_tok_username')
        self.tik_tok_username = attributes[:'tik_tok_username']
      end

      if attributes.key?(:'stack_exchange_url')
        self.stack_exchange_url = attributes[:'stack_exchange_url']
      end

      if attributes.key?(:'stack_overflow_url')
        self.stack_overflow_url = attributes[:'stack_overflow_url']
      end

      if attributes.key?(:'parent_contact_id')
        self.parent_contact_id = attributes[:'parent_contact_id']
      end

      if attributes.key?(:'fax_number')
        self.fax_number = attributes[:'fax_number']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @first_name.nil?
        invalid_properties.push('invalid value for "first_name", first_name cannot be nil.')
      end

      if @first_name.to_s.length > 50
        invalid_properties.push('invalid value for "first_name", the character length must be smaller than or equal to 50.')
      end

      if @first_name.to_s.length < 1
        invalid_properties.push('invalid value for "first_name", the character length must be great than or equal to 1.')
      end

      if !@last_name.nil? && @last_name.to_s.length > 50
        invalid_properties.push('invalid value for "last_name", the character length must be smaller than or equal to 50.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @email.to_s.length < 1
        invalid_properties.push('invalid value for "email", the character length must be great than or equal to 1.')
      end

      if !@tax_id.nil? && @tax_id.to_s.length > 20
        invalid_properties.push('invalid value for "tax_id", the character length must be smaller than or equal to 20.')
      end

      if !@tax_id.nil? && @tax_id.to_s.length < 0
        invalid_properties.push('invalid value for "tax_id", the character length must be great than or equal to 0.')
      end

      if !@primary_contact_id.nil? && @primary_contact_id.to_s.length > 36
        invalid_properties.push('invalid value for "primary_contact_id", the character length must be smaller than or equal to 36.')
      end

      if !@primary_contact_id.nil? && @primary_contact_id.to_s.length < 0
        invalid_properties.push('invalid value for "primary_contact_id", the character length must be great than or equal to 0.')
      end

      if !@about.nil? && @about.to_s.length > 500
        invalid_properties.push('invalid value for "about", the character length must be smaller than or equal to 500.')
      end

      if !@country_id.nil? && @country_id.to_s.length > 3
        invalid_properties.push('invalid value for "country_id", the character length must be smaller than or equal to 3.')
      end

      if !@country_id.nil? && @country_id.to_s.length < 0
        invalid_properties.push('invalid value for "country_id", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/^[\w\s-]{3,10}$/)
      if !@postal_code.nil? && @postal_code !~ pattern
        invalid_properties.push("invalid value for \"postal_code\", must conform to the pattern #{pattern}.")
      end

      if !@duns.nil? && @duns.to_s.length > 9
        invalid_properties.push('invalid value for "duns", the character length must be smaller than or equal to 9.')
      end

      if !@duns.nil? && @duns.to_s.length < 0
        invalid_properties.push('invalid value for "duns", the character length must be great than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["Individual", "Organization"])
      return false unless type_validator.valid?(@type)
      return false if @first_name.nil?
      return false if @first_name.to_s.length > 50
      return false if @first_name.to_s.length < 1
      return false if !@last_name.nil? && @last_name.to_s.length > 50
      return false if @email.nil?
      return false if @email.to_s.length < 1
      return false if !@tax_id.nil? && @tax_id.to_s.length > 20
      return false if !@tax_id.nil? && @tax_id.to_s.length < 0
      return false if !@primary_contact_id.nil? && @primary_contact_id.to_s.length > 36
      return false if !@primary_contact_id.nil? && @primary_contact_id.to_s.length < 0
      return false if !@about.nil? && @about.to_s.length > 500
      return false if !@country_id.nil? && @country_id.to_s.length > 3
      return false if !@country_id.nil? && @country_id.to_s.length < 0
      return false if !@postal_code.nil? && @postal_code !~ Regexp.new(/^[\w\s-]{3,10}$/)
      return false if !@duns.nil? && @duns.to_s.length > 9
      return false if !@duns.nil? && @duns.to_s.length < 0
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["Individual", "Organization"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      if first_name.nil?
        fail ArgumentError, 'first_name cannot be nil'
      end

      if first_name.to_s.length > 50
        fail ArgumentError, 'invalid value for "first_name", the character length must be smaller than or equal to 50.'
      end

      if first_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "first_name", the character length must be great than or equal to 1.'
      end

      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      if !last_name.nil? && last_name.to_s.length > 50
        fail ArgumentError, 'invalid value for "last_name", the character length must be smaller than or equal to 50.'
      end

      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      if email.to_s.length < 1
        fail ArgumentError, 'invalid value for "email", the character length must be great than or equal to 1.'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] tax_id Value to be assigned
    def tax_id=(tax_id)
      if !tax_id.nil? && tax_id.to_s.length > 20
        fail ArgumentError, 'invalid value for "tax_id", the character length must be smaller than or equal to 20.'
      end

      if !tax_id.nil? && tax_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "tax_id", the character length must be great than or equal to 0.'
      end

      @tax_id = tax_id
    end

    # Custom attribute writer method with validation
    # @param [Object] primary_contact_id Value to be assigned
    def primary_contact_id=(primary_contact_id)
      if !primary_contact_id.nil? && primary_contact_id.to_s.length > 36
        fail ArgumentError, 'invalid value for "primary_contact_id", the character length must be smaller than or equal to 36.'
      end

      if !primary_contact_id.nil? && primary_contact_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "primary_contact_id", the character length must be great than or equal to 0.'
      end

      @primary_contact_id = primary_contact_id
    end

    # Custom attribute writer method with validation
    # @param [Object] about Value to be assigned
    def about=(about)
      if !about.nil? && about.to_s.length > 500
        fail ArgumentError, 'invalid value for "about", the character length must be smaller than or equal to 500.'
      end

      @about = about
    end

    # Custom attribute writer method with validation
    # @param [Object] country_id Value to be assigned
    def country_id=(country_id)
      if !country_id.nil? && country_id.to_s.length > 3
        fail ArgumentError, 'invalid value for "country_id", the character length must be smaller than or equal to 3.'
      end

      if !country_id.nil? && country_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "country_id", the character length must be great than or equal to 0.'
      end

      @country_id = country_id
    end

    # Custom attribute writer method with validation
    # @param [Object] postal_code Value to be assigned
    def postal_code=(postal_code)
      pattern = Regexp.new(/^[\w\s-]{3,10}$/)
      if !postal_code.nil? && postal_code !~ pattern
        fail ArgumentError, "invalid value for \"postal_code\", must conform to the pattern #{pattern}."
      end

      @postal_code = postal_code
    end

    # Custom attribute writer method with validation
    # @param [Object] duns Value to be assigned
    def duns=(duns)
      if !duns.nil? && duns.to_s.length > 9
        fail ArgumentError, 'invalid value for "duns", the character length must be smaller than or equal to 9.'
      end

      if !duns.nil? && duns.to_s.length < 0
        fail ArgumentError, 'invalid value for "duns", the character length must be great than or equal to 0.'
      end

      @duns = duns
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          timestamp == o.timestamp &&
          type == o.type &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          email == o.email &&
          tax_id == o.tax_id &&
          primary_contact_id == o.primary_contact_id &&
          qualified_name == o.qualified_name &&
          about == o.about &&
          country_id == o.country_id &&
          state_id == o.state_id &&
          city_id == o.city_id &&
          mobile_phone == o.mobile_phone &&
          business_phone == o.business_phone &&
          postal_code == o.postal_code &&
          duns == o.duns &&
          job_title == o.job_title &&
          web_url == o.web_url &&
          currency_id == o.currency_id &&
          language_id == o.language_id &&
          timezone_id == o.timezone_id &&
          birthday == o.birthday &&
          street_line1 == o.street_line1 &&
          street_line2 == o.street_line2 &&
          git_hub_url == o.git_hub_url &&
          twitch_url == o.twitch_url &&
          reddit_url == o.reddit_url &&
          tik_tok_url == o.tik_tok_url &&
          website_url == o.website_url &&
          twitter_url == o.twitter_url &&
          facebook_url == o.facebook_url &&
          you_tube_url == o.you_tube_url &&
          linked_in_url == o.linked_in_url &&
          instagram_url == o.instagram_url &&
          github_username == o.github_username &&
          instagram_username == o.instagram_username &&
          tik_tok_username == o.tik_tok_username &&
          stack_exchange_url == o.stack_exchange_url &&
          stack_overflow_url == o.stack_overflow_url &&
          parent_contact_id == o.parent_contact_id &&
          fax_number == o.fax_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, timestamp, type, first_name, last_name, email, tax_id, primary_contact_id, qualified_name, about, country_id, state_id, city_id, mobile_phone, business_phone, postal_code, duns, job_title, web_url, currency_id, language_id, timezone_id, birthday, street_line1, street_line2, git_hub_url, twitch_url, reddit_url, tik_tok_url, website_url, twitter_url, facebook_url, you_tube_url, linked_in_url, instagram_url, github_username, instagram_username, tik_tok_username, stack_exchange_url, stack_overflow_url, parent_contact_id, fax_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
