=begin
#ContentService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BlogPostCategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlogPostCategoriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BlogPostCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlogPostCategoriesApi' do
    it 'should create an instance of BlogPostCategoriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BlogPostCategoriesApi)
    end
  end

  # unit tests for count_blog_post_categories_async
  # Count blog post categories
  # Counts all blog post categories for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_blog_post_categories_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_blog_post_category_async
  # Create a blog post category
  # Creates a new blog post category for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [BlogPostCategoryCreateDto] :blog_post_category_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_blog_post_category_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_blog_post_category_async
  # Delete a blog post category
  # Deletes a blog post category for the specified tenant.
  # @param tenant_id 
  # @param blog_post_category_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_blog_post_category_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blog_post_categories_async
  # Get blog post categories
  # Retrieves all blog post categories for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BlogPostCategoryDtoListEnvelope]
  describe 'get_blog_post_categories_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_blog_post_category_by_id_async
  # Get blog post category by ID
  # Retrieves a specific blog post category by its ID.
  # @param tenant_id 
  # @param blog_post_category_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BlogPostCategoryDtoEnvelope]
  describe 'get_blog_post_category_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_blog_post_category_async
  # Update a blog post category
  # Updates an existing blog post category for the specified tenant.
  # @param tenant_id 
  # @param blog_post_category_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [BlogPostCategoryUpdateDto] :blog_post_category_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_blog_post_category_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
