=begin
#SocialService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CurriculumsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CurriculumsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CurriculumsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurriculumsApi' do
    it 'should create an instance of CurriculumsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CurriculumsApi)
    end
  end

  # unit tests for create_curriculum_async
  # Create a curriculum
  # Creates a curriculum (CV) on the specified social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [CurriculumCreateDto] :curriculum_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_curriculum_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_curriculum_async
  # Delete a curriculum
  # Deletes a curriculum authored on the specified social profile.
  # @param social_profile_id 
  # @param curriculum_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_curriculum_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_curriculum_async
  # Get curriculum by ID
  # Retrieves a specific curriculum authored on the specified social profile.
  # @param social_profile_id 
  # @param curriculum_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [CurriculumDtoEnvelope]
  describe 'get_curriculum_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_curriculums_async
  # Get curricula
  # Retrieves the curricula (CVs) authored on the specified social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [CurriculumDtoListEnvelope]
  describe 'get_curriculums_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_curriculums_count_async
  # Count curricula
  # Returns the count of curricula authored on the specified social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_curriculums_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_curriculum_async
  # Patch a curriculum
  # Partially updates an existing curriculum authored on the specified social profile.
  # @param social_profile_id 
  # @param curriculum_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [Array<Operation>] :operation 
  # @return [EmptyEnvelope]
  describe 'patch_curriculum_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_curriculum_async
  # Update a curriculum
  # Updates an existing curriculum authored on the specified social profile.
  # @param social_profile_id 
  # @param curriculum_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id 
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [CurriculumUpdateDto] :curriculum_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_curriculum_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
