=begin
#SocialService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SocialProfilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SocialProfilesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SocialProfilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SocialProfilesApi' do
    it 'should create an instance of SocialProfilesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SocialProfilesApi)
    end
  end

  # unit tests for count_conversations_async
  # Count Conversations
  # Count conversations for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_conversations_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_followed_profiles_async
  # Count Followed Profiles
  # Count followed profiles for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_followed_profiles_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_follower_profiles_async
  # Count Follower Profiles
  # Count follower profiles for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_follower_profiles_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_followers_async
  # Count Followers
  # Count followers for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_followers_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_follows_async
  # Count Follows
  # Count follows for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_follows_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_messages_async
  # Count Messages
  # Count messages for a conversation.
  # @param conversation_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_messages_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_notifications_async
  # Count Notifications
  # Count notifications for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_notifications_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for count_social_profiles_async
  # Count Social Profiles
  # Count social profiles.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'count_social_profiles_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_conversation_async
  # Create Conversation
  # Create a new conversation.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ConversationCreateDto] :conversation_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_conversation_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_message_async
  # Create Message
  # Create a new message.
  # @param social_profile_id 
  # @param conversation_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [PrivateMessageCreateDto] :private_message_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_message_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_message_async
  # Delete Message
  # Delete a message.
  # @param social_profile_id 
  # @param conversation_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_message_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for follow_async
  # Follow
  # Follow a social profile.
  # @param social_profile_id 
  # @param followed_social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'follow_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for follow_exists_async
  # Check if Follow Exists
  # Check if a follow record exists between two social profiles.
  # @param social_profile_id 
  # @param followed_social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [BooleanEnvelope]
  describe 'follow_exists_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_conversations_async
  # Get Conversations
  # Get a list of conversations for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ConversationDtoListEnvelope]
  describe 'get_conversations_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_followed_profiles_async
  # Get Followed Profiles
  # Get a list of followed profiles for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [SocialProfileDtoListEnvelope]
  describe 'get_followed_profiles_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_follower_profiles_async
  # Get Follower Profiles
  # Get a list of follower profiles for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [SocialProfileDtoListEnvelope]
  describe 'get_follower_profiles_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_followers_async
  # Get Followers
  # Get a list of followers for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [FollowRecordDtoListEnvelope]
  describe 'get_followers_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_follows_async
  # Get Follows
  # Get a list of follows for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [FollowRecordDtoListEnvelope]
  describe 'get_follows_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_messages_async
  # Get Messages
  # Get a list of messages for a conversation.
  # @param conversation_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [PrivateMessageDtoListEnvelope]
  describe 'get_messages_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_notifications_async
  # Get Notifications
  # Get a list of notifications for a social profile.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [NotificationDtoListEnvelope]
  describe 'get_notifications_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_social_profile_async
  # Get Social Profile
  # Get a social profile by ID.
  # @param social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [SocialProfileDtoEnvelope]
  describe 'get_social_profile_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_social_profiles_async
  # Get Social Profiles
  # Get a list of social profiles.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [SocialProfileDtoListEnvelope]
  describe 'get_social_profiles_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unfollow_async
  # Unfollow
  # Unfollow a social profile.
  # @param social_profile_id 
  # @param followed_social_profile_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'unfollow_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_message_async
  # Update Message
  # Update a message.
  # @param social_profile_id 
  # @param conversation_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [PrivateMessageUpdateDto] :private_message_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_message_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
