=begin
#LogisticsService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5401
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ItemRestocksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ItemRestocksApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ItemRestocksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ItemRestocksApi' do
    it 'should create an instance of ItemRestocksApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ItemRestocksApi)
    end
  end

  # unit tests for create_item_restock_async
  # Create an item restock
  # Creates a new item restock.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ItemRestockCreateDto] :item_restock_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_item_restock_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_item_restock_entry_async
  # Create a restock entry
  # Creates a new restock entry.
  # @param tenant_id 
  # @param restock_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ItemRestockEntryCreateDto] :item_restock_entry_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_item_restock_entry_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_item_restock_async
  # Delete an item restock
  # Deletes an item restock.
  # @param tenant_id 
  # @param restock_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_item_restock_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_item_restock_entry_async
  # Delete a restock entry
  # Deletes a restock entry.
  # @param tenant_id 
  # @param restock_id 
  # @param entry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_item_restock_entry_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item_restock_by_id_async
  # Get item restock by ID
  # Retrieves a specific item restock.
  # @param tenant_id 
  # @param restock_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ItemRestockDtoEnvelope]
  describe 'get_item_restock_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item_restock_entries_async
  # Get restock entries
  # Retrieves all entries for the specified restock.
  # @param tenant_id 
  # @param restock_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ItemRestockEntryDtoListEnvelope]
  describe 'get_item_restock_entries_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item_restock_entries_count_async
  # Get restock entries count
  # Returns the count of restock entries.
  # @param tenant_id 
  # @param restock_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_item_restock_entries_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item_restock_entry_by_id_async
  # Get restock entry by ID
  # Retrieves a specific restock entry.
  # @param tenant_id 
  # @param restock_id 
  # @param entry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ItemRestockEntryDtoEnvelope]
  describe 'get_item_restock_entry_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item_restocks_async
  # Get all item restocks
  # Retrieves all item restocks for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ItemRestockDtoListEnvelope]
  describe 'get_item_restocks_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_item_restocks_count_async
  # Get item restocks count
  # Returns the count of item restocks.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_item_restocks_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_item_restock_async
  # Update an item restock
  # Updates an existing item restock.
  # @param tenant_id 
  # @param restock_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ItemRestockUpdateDto] :item_restock_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_item_restock_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_item_restock_entry_async
  # Update a restock entry
  # Updates an existing restock entry.
  # @param tenant_id 
  # @param restock_id 
  # @param entry_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [ItemRestockEntryUpdateDto] :item_restock_entry_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_item_restock_entry_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
