=begin
#HrmsService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5401
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PayrollsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayrollsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PayrollsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayrollsApi' do
    it 'should create an instance of PayrollsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PayrollsApi)
    end
  end

  # unit tests for create_payroll_async
  # Create a payroll
  # Creates a new payroll for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [PayrollCreateDto] :payroll_create_dto 
  # @return [EmptyEnvelope]
  describe 'create_payroll_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_payroll_async
  # Delete a payroll
  # Deletes a payroll for the specified tenant.
  # @param tenant_id 
  # @param payroll_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_payroll_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payroll_by_id_async
  # Get payroll by ID
  # Retrieves a specific payroll by its identifier.
  # @param tenant_id 
  # @param payroll_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [PayrollDtoEnvelope]
  describe 'get_payroll_by_id_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payrolls_async
  # Get payrolls
  # Retrieves payrolls for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [PayrollDtoListEnvelope]
  describe 'get_payrolls_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payrolls_count_async
  # Count payrolls
  # Counts payrolls for the specified tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_payrolls_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_payroll_async
  # Update a payroll
  # Updates an existing payroll for the specified tenant.
  # @param tenant_id 
  # @param payroll_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @option opts [PayrollUpdateDto] :payroll_update_dto 
  # @return [EmptyEnvelope]
  describe 'update_payroll_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
