=begin
#TimeTrackerService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ProjectTimeLogUpdateDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ProjectTimeLogUpdateDto do
  let(:instance) { OpenapiClient::ProjectTimeLogUpdateDto.new }

  describe 'test an instance of ProjectTimeLogUpdateDto' do
    it 'should create an instance of ProjectTimeLogUpdateDto' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ProjectTimeLogUpdateDto)
    end
  end

  describe 'test attribute "log_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "time_span"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "comments"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "project_task_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "project_period_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "project_time_log_record_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["RegularHours", "OvertimeToPay", "OvertimeToCompensate"])
      # validator.allowable_values.each do |value|
      #   expect { instance.project_time_log_record_type = value }.not_to raise_error
      # end
    end
  end

end
