=begin
#AccountingService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.2.5401
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ExpenseClaimsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExpenseClaimsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ExpenseClaimsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExpenseClaimsApi' do
    it 'should create an instance of ExpenseClaimsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ExpenseClaimsApi)
    end
  end

  # unit tests for create_expense_claim
  # Create an expense claim
  # Creates a new expense claim.
  # @param tenant_id 
  # @param expense_claim_create_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'create_expense_claim test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_expense_claim
  # Delete an expense claim
  # Deletes an expense claim.
  # @param tenant_id 
  # @param expense_claim_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_expense_claim test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_expense_claim
  # Get an expense claim by id
  # Retrieves an expense claim by its identifier.
  # @param tenant_id 
  # @param expense_claim_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ExpenseClaimDtoEnvelope]
  describe 'get_expense_claim test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_expense_claims
  # Get all expense claims for a tenant
  # Retrieves all expense claims for the specified tenant using OData query options.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [ExpenseClaimDtoListEnvelope]
  describe 'get_expense_claims test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_expense_claims_count
  # Get the count of expense claims for a tenant
  # Retrieves the count of expense claims for the specified tenant using OData query options.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_expense_claims_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_expense_claim
  # Update an expense claim
  # Updates an existing expense claim.
  # @param tenant_id 
  # @param expense_claim_id 
  # @param expense_claim_update_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'update_expense_claim test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
