=begin
#AccountingService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::FinancialBooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FinancialBooksApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::FinancialBooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FinancialBooksApi' do
    it 'should create an instance of FinancialBooksApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::FinancialBooksApi)
    end
  end

  # unit tests for create_financial_book_async
  # Creates a new financial book
  # Creates a new financial book.
  # @param tenant_id 
  # @param financial_book_create_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'create_financial_book_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_financial_book_async
  # Deletes an existing financial book
  # Deletes an existing financial book.
  # @param tenant_id 
  # @param financial_book_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_financial_book_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_financial_book_details_async
  # Gets the details of a specific financial book
  # Gets the details of a specific financial book.
  # @param tenant_id 
  # @param financial_book_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [FinancialBookDtoEnvelope]
  describe 'get_financial_book_details_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_financial_books_async
  # Get all financial books for a tenant
  # Retrieves all financial books for the specified tenant using OData query options.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [FinancialBookDtoListEnvelope]
  describe 'get_financial_books_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_financial_books_count_async
  # Get the count of financial books
  # Get the count of financial books.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_financial_books_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_financial_book_async
  # Updates an existing financial book
  # Updates an existing financial book.
  # @param tenant_id 
  # @param financial_book_id 
  # @param financial_book_update_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'update_financial_book_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
