=begin
#AccountingService

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0.0
Contact: support@fenix-alliance.com
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LoansApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoansApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LoansApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoansApi' do
    it 'should create an instance of LoansApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LoansApi)
    end
  end

  # unit tests for create_loan_application_async
  # Creates a loan application
  # Creates a new loan application.
  # @param tenant_id 
  # @param loan_application_create_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'create_loan_application_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_loan_async
  # Creates a new loan
  # Creates a new loan for the current tenant.
  # @param tenant_id 
  # @param loan_create_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'create_loan_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_loan_application_async
  # Deletes a loan application
  # Deletes the specified loan application.
  # @param tenant_id 
  # @param application_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_loan_application_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_loan_async
  # Deletes a loan
  # Deletes the specified loan.
  # @param tenant_id 
  # @param loan_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'delete_loan_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loan_application_details_async
  # Gets a loan application by ID
  # Retrieves the details of a loan application.
  # @param tenant_id 
  # @param application_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [LoanApplicationDtoEnvelope]
  describe 'get_loan_application_details_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loan_applications_async
  # Gets all loan applications
  # Retrieves all loan applications for the current tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [LoanApplicationDtoIReadOnlyListEnvelope]
  describe 'get_loan_applications_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loan_applications_count_async
  # Counts loan applications
  # Gets the count of loan applications for the current tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_loan_applications_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loan_details_async
  # Gets a loan by ID
  # Retrieves the details of a loan using its unique ID.
  # @param tenant_id 
  # @param loan_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [LoanDtoEnvelope]
  describe 'get_loan_details_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loans_async
  # Gets all loans
  # Retrieves all loans for the current tenant with OData support.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [LoanDtoIReadOnlyListEnvelope]
  describe 'get_loans_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_loans_count_async
  # Counts loans
  # Gets the count of loans for the current tenant.
  # @param tenant_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [Int32Envelope]
  describe 'get_loans_count_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_loan_application_async
  # Updates a loan application
  # Updates the specified loan application.
  # @param tenant_id 
  # @param application_id 
  # @param loan_application_update_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'update_loan_application_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_loan_async
  # Updates a loan
  # Updates the specified loan.
  # @param tenant_id 
  # @param loan_id 
  # @param loan_update_dto 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_version 
  # @option opts [String] :x_api_version 
  # @return [EmptyEnvelope]
  describe 'update_loan_async test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
